### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by Akryum** [nickmessing/babel-plugin-jsx-event-modifiers#2]
I get an error while using this plugin that is included in [babel-preset-vue](https://github.com/vuejs/babel-preset-vue) (I'm using webpack 3):

```
Module build failed: TypeError: src/components/Link.vue: Cannot read property 'type' of undefined
    at JSXOpeningElement.path.node.attributes.forEach.attribute (node_modules\babel-plugin-jsx-event-modifiers\index.js:112:33)
    at Array.forEach (native)
    at JSXOpeningElement (node_modules\babel-plugin-jsx-event-modifiers\index.js:111:34)
    at NodePath._call (node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (node_modules\babel-traverse\lib\index.js:114:17)
    at NodePath.visit (node_modules\babel-traverse\lib\path\context.js:115:19)
    at TraversalContext.visitQueue (node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (node_modules\babel-traverse\lib\index.js:114:17)
    at NodePath.visit (node_modules\babel-traverse\lib\path\context.js:115:19)
 @ ./src/components/Link.vue 4:0-117
```

Here is the component render function:

```jsx
return <a {...data} class={{ 'link-disabled': !props.enabled }} onClick={handleClick}>{children}</a>
```

My `.babelrc`:

```json
{
  "presets": [
    ["env", { "modules": false }],
    "stage-0",
    "vue"
  ]
}
```

**Comment by egoist** [comment]
Seems this bug only happens when you're using *JSX Spread Attributes*

https://jsx.egoist.moe/gist/3bd876165dc9b5bed47755b7b4a7103f
